name: wordzoo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.10+10
#version: 1.0.0+0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  intl_utils: ^2.8.16
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  equatable: ^2.1.0
  gap: ^3.0.1
  # Supabase
  supabase_flutter: ^2.17.2
  share_plus: ^13.3.0
  # UI / Responsive
  responsive_framework: ^1.5.1
  flutter_animate: ^4.5.2

  # Media
  audioplayers: ^6.8.1
  cached_network_image: ^3.4.1

  # Storage
  shared_preferences: ^2.5.5
  universal_html: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Background sync
  workmanager: ^0.10.7

  # Payments
  in_app_purchase: ^3.3.0

  # Code generation
  json_annotation: ^4.12.0

  # Logging
  logger: ^2.7.0

  # Utils
  flutter_dotenv: ^6.0.1
  path_provider: ^2.1.6
  google_mobile_ads: ^9.1.0

  flutter_localizations:
    sdk: flutter

  # Google Fonts
  google_fonts: ^8.2.1

  cupertino_icons: ^1.0.9
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  archive: ^4.1.0
  percent_indicator: ^4.2.5
  syncfusion_flutter_sliders: ^34.2.4
  dropdown_button2: ^3.1.0
  applovin_max: ^4.6.4
  app_version_update: ^7.0.0
  flutter_in_store_app_version_checker: ^3.0.0
  package_info_plus: ^10.2.1
  auto_size_text: ^3.0.0
dependency_overrides:
  meta: ^1.19.0
  jni: 1.0.0
  # Localization
  intl: ^0.20.3
  flutter_native_splash: ^2.4.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.16.0
  json_serializable: ^6.14.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/background/
    - assets/category_card/
    - assets/sub_category_avata/
    - assets/sub_category_avata/plants/
    - assets/sub_category_avata/animals/
    - assets/sub_category_avata/human_relations/
    - assets/sub_category_avata/vehicles/
    - assets/audio/
    - assets/icons/
    - lib/presentation/screens/entity/
    - assets/entity_animations_frame/
    - assets/sounds/animation/
    - assets/sounds/ui/

flutter_assets_generator:
  output_dir: generated/
  output_filename: assets
  class_name: Assets
  auto_detection: true
  # Automatically add missing dependencies (rive, flutter_svg, lottie) default: true
  auto_add_dependencies: true
  # Options: robust (default), legacy (old style)
  style: robust
  package_parameter_enabled: false
  named_with_parent: true
  path_ignore: [ ]


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/AppIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_intl:
  enabled: true