import json
import re
import subprocess
import shutil
import time
from pathlib import Path

import requests


# ============================================================
# CONFIG
# ============================================================

INPUT_JSON = "data_version1_final.json"
OUTPUT_JSON = "wordzoo_translated.json"

OLLAMA_URL = "http://127.0.0.1:11434/api/generate"

TRANSLATE_MODEL = "translategemma:12b"

# Number of entities sent to TranslateGemma at once
BATCH_SIZE = 10

# Languages to add using TranslateGemma
TRANSLATE_LANGUAGES = [
    "es",
    "fr",
    "ja",
    "ko",
]

# Pronunciation generated by eSpeak NG
PRONUNCIATION_LANGUAGES = [
    "vi",
    "es",
    "fr",
    "ja",
    "ko",
]

# Retry
MAX_RETRIES = 3

REQUEST_TIMEOUT = 300

# Delay between Ollama requests
OLLAMA_DELAY = 0.2


# ============================================================
# eSpeak NG language mapping
# ============================================================

ESPEAK_LANGUAGES = {
    "vi": "vi",
    "es": "es",
    "fr": "fr",
    "ja": "ja",
    "ko": "ko",
}


# ============================================================
# Find eSpeak NG
# ============================================================

def find_espeak():

    candidates = [

        "espeak-ng",

        "espeak-ng.exe",

        r"C:\Program Files\eSpeak NG\espeak-ng.exe",

        r"C:\Program Files\eSpeak NG\espeak-ng.exe",

        r"C:\Program Files (x86)\eSpeak NG\espeak-ng.exe",

    ]

    for candidate in candidates:

        path = shutil.which(candidate)

        if path:
            return path

        if Path(candidate).exists():
            return candidate

    return None


ESPEAK_PATH = find_espeak()


# ============================================================
# Utility
# ============================================================

def chunks(items, size):

    for i in range(
        0,
        len(items),
        size
    ):

        yield items[
            i:i + size
        ]


def clean_text(value):

    if not isinstance(value, str):
        return ""

    return value.strip()


def normalize_ipa(value):

    if not value:
        return ""

    value = value.strip()

    # Remove surrounding brackets
    value = value.strip(
        "/[]"
    )

    # Remove eSpeak separator
    value = value.replace(
        "_",
        " "
    )

    # Normalize whitespace
    value = re.sub(
        r"\s+",
        " ",
        value
    )

    return value.strip()


def make_syllable(
        text,
        language
):

    """
    eSpeak does not directly provide the
    human-friendly syllable representation
    used by WordZoo.

    Therefore use a simple fallback.

    IPA remains the authoritative pronunciation.
    """

    if not text:
        return ""

    return text.strip()


# ============================================================
# eSpeak IPA
# ============================================================

def generate_ipa(
        text,
        language
):

    if not ESPEAK_PATH:

        raise RuntimeError(
            "eSpeak NG not found. "
            "Install eSpeak NG and make sure "
            "espeak-ng.exe is available."
        )

    voice = ESPEAK_LANGUAGES.get(
        language
    )

    if not voice:
        return None

    command = [

        ESPEAK_PATH,

        "-q",

        "--ipa=3",

        "-v",
        voice,

        text,

    ]

    try:

        result = subprocess.run(

            command,

            stdout=subprocess.PIPE,

            stderr=subprocess.PIPE,

            text=True,

            encoding="utf-8",

            errors="replace",

            timeout=30,

        )

    except subprocess.TimeoutExpired:

        print(
            f"    ✗ eSpeak timeout: "
            f"{language}: {text}"
        )

        return None

    except Exception as e:

        print(
            f"    ✗ eSpeak error: "
            f"{language}: {e}"
        )

        return None

    if result.returncode != 0:

        print(
            f"    ✗ eSpeak failed: "
            f"{language}: {text}"
        )

        if result.stderr:
            print(
                "      ",
                result.stderr.strip()
            )

        return None

    ipa = normalize_ipa(
        result.stdout
    )

    if not ipa:
        return None

    return ipa


# ============================================================
# Pronunciation
# ============================================================

def generate_pronunciation(
        text,
        language
):

    ipa = generate_ipa(
        text,
        language
    )

    if not ipa:
        return None

    return {

        "ipa": ipa,

        "syllable": make_syllable(
            text,
            language
        ),

    }


# ============================================================
# Load / Save
# ============================================================

def load_json():

    with open(
        INPUT_JSON,
        "r",
        encoding="utf-8"
    ) as f:

        return json.load(f)


def save_json(data):

    tmp_file = OUTPUT_JSON + ".tmp"

    with open(
        tmp_file,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            data,
            f,
            ensure_ascii=False,
            indent=2
        )

    Path(tmp_file).replace(
        OUTPUT_JSON
    )


# ============================================================
# Collect entities
# ============================================================

def collect_entities(data):

    entities = []

    for category in data.get(
        "categories",
        []
    ):

        for subcategory in category.get(
            "subcategories",
            []
        ):

            for entity in subcategory.get(
                "entities",
                []
            ):

                entities.append(
                    entity
                )

    return entities


# ============================================================
# Missing names
# ============================================================

def missing_names(
        entity
):

    names = entity.get(
        "names",
        {}
    )

    missing = []

    for language in TRANSLATE_LANGUAGES:

        value = names.get(
            language
        )

        if not isinstance(
            value,
            str
        ) or not value.strip():

            missing.append(
                language
            )

    return missing


# ============================================================
# TranslateGemma prompt
# ============================================================

def build_translation_prompt(
        batch
):

    items = []

    for entity in batch:

        names = entity.get(
            "names",
            {}
        )

        source = {

            "id": entity.get(
                "id"
            ),

            "vi": names.get(
                "vi",
                ""
            ),

            "en": names.get(
                "en",
                ""
            ),

            "zh": names.get(
                "zh",
                ""),

            "missing": missing_names(
                entity
            )

        }

        items.append(
            source
        )

    prompt = f"""
You are translating WordZoo vocabulary.

Return ONLY valid JSON.

Do not return markdown.
Do not return explanations.
Do not return code fences.

For every item, translate ONLY the languages
listed in "missing".

Target languages:

es = Spanish
fr = French
ja = Japanese
ko = Korean

IMPORTANT:

1. Preserve the "id" exactly.
2. Do NOT modify vi.
3. Do NOT modify en.
4. Do NOT modify zh.
5. Do NOT translate the id.
6. Use natural vocabulary suitable for a children's
   educational vocabulary app.
7. For animals, objects, people, food, etc.,
   use the normal common word.
8. Return one object for every input item.

Format:

[
  {{
    "id": "lion",
    "names": {{
      "es": "León",
      "fr": "Lion",
      "ja": "ライオン",
      "ko": "사자"
    }}
  }}
]

INPUT:

{json.dumps(
    items,
    ensure_ascii=False,
    indent=2
)}
"""

    return prompt


# ============================================================
# Call TranslateGemma
# ============================================================

def call_translategemma(
        batch
):

    prompt = build_translation_prompt(
        batch
    )

    payload = {

        "model": TRANSLATE_MODEL,

        "prompt": prompt,

        "stream": False,

        "options": {

            "temperature": 0,

        },

    }

    for attempt in range(
        1,
        MAX_RETRIES + 1
    ):

        try:

            response = requests.post(

                OLLAMA_URL,

                json=payload,

                timeout=REQUEST_TIMEOUT

            )

            response.raise_for_status()

            result = response.json()

            text = result.get(
                "response",
                ""
            )

            text = text.strip()

            # Remove accidental markdown
            text = re.sub(
                r"^```json\s*",
                "",
                text,
                flags=re.IGNORECASE
            )

            text = re.sub(
                r"\s*```$",
                "",
                text
            )

            data = json.loads(
                text
            )

            if not isinstance(
                data,
                list
            ):

                raise ValueError(
                    "Model did not return a JSON array"
                )

            return data

        except Exception as e:

            print(
                f"    ✗ Attempt "
                f"{attempt}/{MAX_RETRIES}: "
                f"{e}"
            )

            if attempt < MAX_RETRIES:

                time.sleep(
                    attempt * 2
                )

    return []


# ============================================================
# Merge translations
# ============================================================

def merge_translations(
        entities,
        results
):

    entity_map = {

        entity.get("id"): entity

        for entity in entities

    }

    success = 0

    failed = 0

    for result in results:

        if not isinstance(
            result,
            dict
        ):
            continue

        entity_id = result.get(
            "id"
        )

        entity = entity_map.get(
            entity_id
        )

        if not entity:
            failed += 1
            continue

        translated_names = result.get(
            "names",
            {}
        )

        if not isinstance(
            translated_names,
            dict
        ):
            failed += 1
            continue

        names = entity.setdefault(
            "names",
            {}
        )

        changed = False

        for language in TRANSLATE_LANGUAGES:

            value = translated_names.get(
                language
            )

            # IMPORTANT:
            # NEVER overwrite existing data
            if language in names:
                continue

            if not isinstance(
                value,
                str
            ):
                continue

            value = value.strip()

            if not value:
                continue

            names[language] = value

            changed = True

        if changed:
            success += 1

    return success, failed


# ============================================================
# Generate pronunciation
# ============================================================

def process_pronunciation(
        entities
):

    print()
    print("=" * 70)
    print("GENERATE PRONUNCIATION - eSpeak NG")
    print("=" * 70)

    total = (
        len(entities)
        *
        len(PRONUNCIATION_LANGUAGES)
    )

    processed = 0

    success = 0

    failed = 0

    for language in PRONUNCIATION_LANGUAGES:

        print()
        print(
            f"Language: {language}"
        )

        for entity in entities:

            names = entity.get(
                "names",
                {}
            )

            text = names.get(
                language
            )

            if not text:
                failed += 1
                processed += 1
                continue

            pronunciation = generate_pronunciation(
                text,
                language
            )

            if pronunciation:

                entity.setdefault(
                    "pronunciation",
                    {}
                )[language] = pronunciation

                success += 1

            else:

                failed += 1

            processed += 1

            if processed % 100 == 0:

                print(
                    f"  Progress: "
                    f"{processed:,}/"
                    f"{total:,}"
                )

    print()
    print(
        f"Pronunciation done: "
        f"success={success:,}, "
        f"failed={failed:,}"
    )


# ============================================================
# Main
# ============================================================

def main():

    global ESPEAK_PATH

    print()
    print("=" * 70)
    print("WORDZOO TRANSLATEGEMMA + ESPEAK NG")
    print("=" * 70)

    # --------------------------------------------------------
    # Check eSpeak
    # --------------------------------------------------------

    ESPEAK_PATH = find_espeak()

    if not ESPEAK_PATH:

        print()
        print(
            "ERROR: eSpeak NG was not found."
        )

        print()
        print(
            "Install eSpeak NG first."
        )

        print(
            "Then make sure espeak-ng.exe "
            "is in PATH."
        )

        return

    print(
        f"eSpeak NG: {ESPEAK_PATH}"
    )

    # --------------------------------------------------------
    # Load
    # --------------------------------------------------------

    print(
        f"Input: {INPUT_JSON}"
    )

    data = load_json()

    entities = collect_entities(
        data
    )

    print(
        f"Entities: {len(entities):,}"
    )

    # --------------------------------------------------------
    # Translation
    # --------------------------------------------------------

    translation_entities = [

        entity

        for entity in entities

        if missing_names(
            entity
        )

    ]

    print(
        f"Entities needing translation: "
        f"{len(translation_entities):,}"
    )

    batches = list(
        chunks(
            translation_entities,
            BATCH_SIZE
        )
    )

    translation_success = 0

    translation_failed = 0

    for batch_index, batch in enumerate(
        batches,
        start=1
    ):

        start = (
            (batch_index - 1)
            *
            BATCH_SIZE
            +
            1
        )

        end = (
            start
            +
            len(batch)
            -
            1
        )

        print()
        print(
            f"BATCH "
            f"{start}-{end}"
        )

        print(
            "Entities:"
        )

        print(
            "  "
            +
            ", ".join(
                entity["id"]
                for entity in batch
            )
        )

        print(
            "  → TranslateGemma 12B..."
        )

        results = call_translategemma(
            batch
        )

        print(
            f"  ✓ Model returned "
            f"{len(results)} results"
        )

        success_count, failed_count = (
            merge_translations(
                batch,
                results
            )
        )

        translation_success += (
            success_count
        )

        translation_failed += (
            failed_count
        )

        print(
            f"  ✓ merged="
            f"{success_count} "
            f"failed="
            f"{failed_count}"
        )

        # Save after every batch
        save_json(
            data
        )

        time.sleep(
            OLLAMA_DELAY
        )

    # --------------------------------------------------------
    # Pronunciation
    # --------------------------------------------------------

    process_pronunciation(
        entities
    )

    # --------------------------------------------------------
    # Final save
    # --------------------------------------------------------

    save_json(
        data
    )

    print()
    print("=" * 70)
    print("COMPLETED")
    print("=" * 70)

    print(
        f"Translation success: "
        f"{translation_success:,}"
    )

    print(
        f"Translation failed: "
        f"{translation_failed:,}"
    )

    print(
        f"Output: {OUTPUT_JSON}"
    )


if __name__ == "__main__":

    main()